packages:
  - 'packages/*'
  - 'extensions/*'
  - 'extensions/*/packages/*'
  - 'scripts'
  - 'tests/playwright'
onlyBuiltDependencies:
  - '@biomejs/biome'
  - core-js
  - core-js-pure
  - cpu-features
  - electron
  - esbuild
  - msw
  - protobufjs
  - sharp
  - ssh2
  - svelte-preprocess
  - win-ca
  - 'better-sqlite3'
