apiVersion: v1
kind: Secret
metadata:
  name: goose-google-credentials
  labels:
    app: goose
  annotations:
    kortex-hub/version: 1.0.0
  namespace: default
stringData:
    GOOGLE_API_KEY: dummy
---
apiVersion: batch/v1
kind: Job
metadata:
  name: goose-recipe-echo
  labels:
    app: goose
  annotations:
    kortex-hub/version: 1.0.0
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: goose
          image: quay.io/jotnar/goose:latest
          command: ['/usr/local/bin/goose']
          args: ['run', '--recipe', '/home/goose/recipe.yaml']
          envFrom:
            - secretRef:
                name: goose-google-credentials
          volumeMounts:
            - name: goose-recipe-volume
              mountPath: /home/goose/recipe.yaml
              subPath: recipe.yaml
      volumes:
        # Goose recipe
        - name: goose-recipe-volume
          configMap:
            name: goose-recipe-echo
      restartPolicy: Never
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: goose-recipe-echo
  labels:
    app: goose
  annotations:
    kortex-hub/version: 1.0.0
  namespace: default
data:
  recipe.yaml: |
    title: "Paris Explorer"
    name: "Paris Explorer"
    description: "Paris Explorer"
    
    # Required for headless mode
    prompt: "Plan a 7 days trip in Paris, mention per day the planning, starting on monday."
    
    instructions: |
      Your task is to:
      1. List the important monuments
      2. Plan each day of the trip
          
